<script type="text/javascript" src="<?php echo base_url('public/Back/assets/js/jquery-1.11.3.min.js'); ?>"></script>	
<script type="text/javascript" src="<?php echo base_url('public/Back/assets/js/bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/Back/assets/js/bootstrap-filestyle.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/Back/assets/js/jquery.mousewheel-3.0.6.pack.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/Back/assets/js/jquery.fancybox.pack.js'); ?>"></script>	
<script type="text/javascript" src="<?php echo base_url('public/Back/assets/js/jquery.maskedinput.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/Back/assets/js/jquery.maskMoney.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/Back/assets/js/chosen.jquery.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/Back/assets/js/datatables.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/Back/assets/js/bootstrap-select.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/Back/assets/js/bootstrap-select-pt_BR.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/Back/assets/js/bootstrap-tooltip.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/Back/assets/js/bootstrap-confirmation.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/Back/assets/js/iconset-all.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/Back/assets/js/bootstrap-iconpicker.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/Back/assets/js/jscolor.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/Back/assets/js/jquery-confirm.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/Back/assets/js/mask.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/Back/assets/js/scripts.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('public/Back/assets/js/custom.js?'.date('YmdHis')); ?>"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>